"""empty message

Revision ID: 7a4a6abfea3e
Revises: f5e9032bea80
Create Date: 2024-05-15 14:37:19.044304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a4a6abfea3e'
down_revision = 'f5e9032bea80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('property_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_name', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
