"""empty message

Revision ID: 86e8761239dd
Revises: 25e5fc4b8b49
Create Date: 2024-05-20 08:58:08.078615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86e8761239dd'
down_revision = '25e5fc4b8b49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prop_price', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('prop_price')

    # ### end Alembic commands ###
