"""empty message

Revision ID: b2b9753ac970
Revises: caea284f4a13
Create Date: 2024-05-13 16:12:41.616041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2b9753ac970'
down_revision = 'caea284f4a13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('request_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_email', sa.String(length=20), nullable=True),
    sa.Column('request_subject', sa.String(length=100), nullable=True),
    sa.Column('request_content', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    # ### end Alembic commands ###
