"""empty message

Revision ID: caea284f4a13
Revises: 
Create Date: 2024-05-07 11:08:52.266937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caea284f4a13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_username', sa.String(length=20), nullable=True),
    sa.Column('admin_pwd', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('prop_type',
    sa.Column('prop_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prop_type_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('prop_type_id')
    )
    op.create_table('state',
    sa.Column('state_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('state_id')
    )
    op.create_table('lga',
    sa.Column('lga_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lga_name', sa.String(length=200), nullable=False),
    sa.Column('lga_stateid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lga_stateid'], ['state.state_id'], ),
    sa.PrimaryKeyConstraint('lga_id')
    )
    op.create_table('property',
    sa.Column('property_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_adddress', sa.String(length=255), nullable=False),
    sa.Column('number_of_rooms', sa.String(length=100), nullable=False),
    sa.Column('number_of_bathrooms', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('prop_type_id', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('lga_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lga_id'], ['lga.lga_id'], ),
    sa.ForeignKeyConstraint(['prop_type_id'], ['prop_type.prop_type_id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['state.state_id'], ),
    sa.PrimaryKeyConstraint('property_id')
    )
    op.create_table('prop_images',
    sa.Column('prop_images_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_file', sa.String(length=255), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.property_id'], ),
    sa.PrimaryKeyConstraint('prop_images_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prop_images')
    op.drop_table('property')
    op.drop_table('lga')
    op.drop_table('state')
    op.drop_table('prop_type')
    op.drop_table('admin')
    # ### end Alembic commands ###
