"""empty message

Revision ID: dc78094b5452
Revises: 7a4a6abfea3e
Create Date: 2024-05-16 05:20:08.001123

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc78094b5452'
down_revision = '7a4a6abfea3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prop_images', schema=None) as batch_op:
        batch_op.drop_constraint('prop_images_ibfk_1', type_='foreignkey')
        batch_op.drop_column('property_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prop_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('prop_images_ibfk_1', 'property', ['property_id'], ['property_id'])

    # ### end Alembic commands ###
