"""empty message

Revision ID: f5e9032bea80
Revises: cad79462c501
Create Date: 2024-05-15 14:20:09.707088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f5e9032bea80'
down_revision = 'cad79462c501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('property_address', sa.String(length=255), nullable=False))
        batch_op.alter_column('number_of_rooms',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('number_of_bathrooms',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('property_adddress')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_adddress', mysql.VARCHAR(length=255), nullable=False))
        batch_op.alter_column('number_of_bathrooms',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('number_of_rooms',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('property_address')
        batch_op.drop_column('property_name')

    # ### end Alembic commands ###
